CREATE TABLE MEMBER(
    MID NVARCHAR2(20) CONSTRAINT PK_MID PRIMARY KEY,
    MPASSWORD NVARCHAR2(20) NOT NULL,
    MNAME NVARCHAR2(20) NOT NULL,
    MPHONE NVARCHAR2(20),
    MEMAIL NVARCHAR2(20),
    MFILE NVARCHAR2(50)
    --MFOLLOW NVARCHAR2(100),
    --MUNFOLLOW NVARCHAR2(100)
);
ALTER TABLE MEMBER ADD(MFOLLOW NVARCHAR2(100));

SELECT * FROM MEMBER;
DROP TABLE MEMBER;

CREATE TABLE BOARD(
    BNUMBER NUMBER(6) CONSTRAINT PK_BNUMBER PRIMARY KEY,
    BWRITER NVARCHAR2(20) NOT NULL,
    BTITLE NVARCHAR2(10) NOT NULL,
    BCONTENT NVARCHAR2(500),
    BCATEGORY NVARCHAR2(20) NOT NULL, 
    BFILE NVARCHAR2(50),
    BDATE DATE,
    BLIKE NUMBER(6),
    BHITS NUMBER(6)
);

DROP TABLE BOARD;
SELECT * FROM BOARD;
CREATE TABLE FOLLOW(
    FNUMBER NUMBER(6) CONSTRAINT PK_FNUMBER PRIMARY KEY,
    FFOLLOW NVARCHAR2(500)
    
);
SELECT * FROM FOLLOW;
ALTER TABLE FOLLOW RENAME COLUMN FFOLLOW TO MFOLLOW;
ALTER TABLE FOLLOW ADD(MID NVARCHAR2(500));

CREATE SEQUENCE FOLLOW_SEQ
    START WITH 1 --시작번호
    INCREMENT BY 1 --몇번씩 증가할건가
    NOCACHE; --임시저장(다음날해도 전날에 썼던 수 부터 시작)


SELECT DISTINCT MID FROM FOLLOW WHERE MFOLLOW = 'dhoon' ;

SELECT MID FROM FOLLOW GROUP BY MFOLLOW 'dhoon';

SELECT MID FROM FOLLOW GROUP BY MID;
